---
title: "GraphsPlots"
author: "Rajeev"
date: "June 4, 2016"
output:
  html_document:
    keep_md: True
---

```{r}
require(gdata)
require(plyr) #Added by Monnie McGee
#install the gdata and plyr packages and load in to R.
library(plyr)
library(gdata)
```

```{r}
setwd("../Paper")
#setwd("/Users/rajeevkumar/GitHub/LiveSessionHomeWork4Bronx/Data")
## You need a perl interpreter to do this on Windows.
## It's automatic in Mac
bk <- read.xls("../Data/rollingsales_bronx.xls",pattern="BOROUGH")
# So, save the file as a csv and use read.csv instead
# bk <- read.csv("rollingsales_bronx.csv",skip=4,header=TRUE)
```




```{r}
## clean/format the data with regular expressions
# We create a new variable that is a "clean' version of sale.price.
bk$SALE.PRICE.N <- as.numeric(gsub("[^[:digit:]]","", bk$SALE.PRICE))
count(is.na(bk$SALE.PRICE.N))
```

```{r}
names(bk) <- tolower(names(bk)) # make all variable names lower case
## Get rid of leading digits
bk$gross.sqft <- as.numeric(gsub("[^[:digit:]]","", bk$gross.square.feet))
bk$land.sqft <- as.numeric(gsub("[^[:digit:]]","", bk$land.square.feet))
bk$year.built <- as.numeric(as.character(bk$year.built))
```

```{r}
## keep only the actual sales
bk.sale <- bk[bk$sale.price.n!=0,]
plot(bk.sale$gross.sqft,bk.sale$sale.price.n)
## Beacuse of wide range of price and size, it is not possible to get any trend or conclusion from above graph.
plot(log10(bk.sale$gross.sqft),log10(bk.sale$sale.price.n))
## As per this graphs, price of most of properties increases with increase in area.
```

```{r}
## for now, let's look at 1-, 2-, and 3-family homes
bk.homes <- bk.sale[which(grepl("FAMILY",bk.sale$building.class.category)),]
dim(bk.homes)
plot(log10(bk.homes$gross.sqft),log10(bk.homes$sale.price.n))
#From above graph, one can conclude that prices remain flat with size. However, there are many sales which doesn't look like actual sales.

summary(bk.homes[which(bk.homes$sale.price.n<100000),])


```

```{r}
## remove outliers that seem like they weren't actual sales
bk.homes$outliers <- (log10(bk.homes$sale.price.n) <=5) + 0
bk.homes <- bk.homes[which(bk.homes$outliers==0),]
plot(log(bk.homes$gross.sqft),log(bk.homes$sale.price.n))
summary(bk.homes[which(bk.homes$sale.price.n>=100000),])
## For home properties , price of majority of properties increases with increase in their flat size. However, there are many properties, where prices either remain flat or decreased with increase in flat size.
```

```{r}
## for now, let's look at 1-, 2-, and 3-family homes at BAYCHESTER                                         
bk.homes.baychester <- bk.homes[which(grepl("BAYCHESTER",bk.homes$neighborhood)),]

plot(log(bk.homes.baychester$gross.sqft), log(bk.homes.baychester$sale.price.n))
summary(bk.homes.baychester[which(bk.homes.baychester$sale.price.n>=100000),])
## For home properties at BAYCHESTER, price of majority of properties increases with increase in their flat size. However, there are many properties, where prices either remain flat or decreased with increase in flat size.

```

```{r}
## for now, let's look at Rental Buildings
bk.rentals <- bk.sale[which(grepl("RENTALS",bk.sale$building.class.category)),]
dim(bk.rentals)
plot(log10(bk.rentals$gross.sqft),log10(bk.rentals$sale.price.n))
summary(bk.rentals[which(bk.rentals$sale.price.n<100000),])

```

```{r}
## remove outliers that seem like they weren't actual sales
bk.rentals$outliers <- (log10(bk.rentals$sale.price.n) <=5) + 0
bk.rentals <- bk.homes[which(bk.rentals$outliers==0),]
plot(log(bk.rentals$gross.sqft),log(bk.rentals$sale.price.n))
summary(bk.rentals[which(bk.rentals$sale.price.n>=100000),])
## For rental properties, price of majority of properties increases with increase in their flat size. However, there are many properties, where prices either remain flat or decreased with increase in flat size.
```

```{r}
sessionInfo()
```

